apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: cats-golang-aria-credentials
  annotations:    
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/name: cats
    app.kubernetes.io/part-of: micropets    
    app.kubernetes.io/component: run
spec:
  name: app-config-aria
  service:
    apiVersion: v1
    kind: Secret
    name: aria-credentials
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: cats-golang
  env:
    - key: observability.enable
      name: MP_OBSERVABILITY.ENABLE
    - key: observability.token
      name: MP_OBSERVABILITY.TOKEN

