---
apiVersion: v1
kind: Secret
metadata:
  name: cats-config-not-used
  labels:
    app.kubernetes.io/part-of: cats
type: Opaque
stringData:
  type: app-configuration
  pets_config.yaml: |-    
    service:
      port: ":8181"
      listen: "true"
      mode: RANDOM_NUMBER
      frequencyError: 10
      delay:
        period: 200
        amplitude: 0.3
      from: Europ YAML
    observability:
      enable: true
      application: micropets
      service: cats
      cluster: us-west
      shard: primary
      server: https://binz.wavefront.com
      token: x-y-z-y
