apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: cats-golang
  namespace: micropets-int
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    #apps.tanzu.vmware.com/carvel-package-workflow: "true"
    app.kubernetes.io/part-of: micropets
    app.kubernetes.io/name: cats
    micropets/kind: backend
spec:
  source:
    git:
      url: https://github.com/bmoussaud/micropets-cats-golang.git
      ref:
        branch: main
  serviceClaims:
    - name: app-config
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: cats-config
  params:
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test-golang
    - name: gitops_commit_message
      value: cats dev supplychain@cluster.local
